/**
 * Copyright (C) 2010-2013 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX. If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx.hooks.events;

import javax.annotation.Nullable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import org.pircbotx.PircBotX;
import org.pircbotx.User;
import org.pircbotx.hooks.Event;
import org.pircbotx.hooks.types.GenericUserEvent;

/**
 * Called whenever an ACTION is sent from a user. E.g. such events generated by
 * typing "/me goes shopping" in most IRC clients.
 *
 * @author Leon Blakey <lord.quackstar at gmail.com>
 * @param <T>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class AwayEvent<T extends PircBotX> extends Event<T> implements GenericUserEvent<T> {

    @Getter(onMethod_={@Override})
    protected final User user;
    protected final String awayMessage;

    /**
     * Default constructor to setup object. Timestamp is automatically set to
     * current time as reported by {@link System#currentTimeMillis() }
     *
     * @param bot The bot object
     * @param user The user object representing the user that sent the message
     * @param awayMessage The action carried out by the user.
     */
    public AwayEvent(T bot, @NonNull User user, @NonNull String awayMessage) {
        super(bot);
        this.user = user;
        this.awayMessage = awayMessage;
    }

    /**
     * Does NOT respond! This will throw an
     * {@link UnsupportedOperationException} since we can't respond to a user
     * that just quit
     *
     * @param response The response to send
     */
    @Override
    @Deprecated
    public void respond(@Nullable String response) {
        throw new UnsupportedOperationException("Attempting to respond to a user that quit");
    }
    
    public String getAwayMessage() {
        return awayMessage;
    }

}
